type:  webdav # filepath, webdav
webdav_url: drive.domain.com
webdav_path: remote.php/webdav
webdav_directory: /Documents/Notes/
webdav_login: admin # dav login
webdav_password: password # dav pass
todoist_token: '00000000000000000000000000000'
todoist_project: 'Inbox'
max_items: 0
filename_output: todoist_todo.txt