webdav_url: drive.domain.com # Use None or False if you don't wish to copy to webdav
webdav_path: remote.php/webdav
webdav_directory: /Documents/Notes/
webdav_login: admin # dav login
webdav_password: password # dav pass
todoist_token: 'XXXXXXXXXXXXXXXXXXXXXXXXX'
todoist_project: 'Today'
todoist_append_inbox: True
max_items: 0
filename_output: todoist_todo.txt
export_file_as: False # Full path where to copy the file to. Must include filename
show_completed_tasks: yes
clean_up_completed_tasks: yes  # Auto remove completed tasks from Todoist. Currently required to stay as Yes. If you dont like it downgrade to previous versions and wait for an update.
todoist_inbox_hide_lowpriority: True  # Will hide priority level D
test_only: False
show_creation_date: no
show_completion_date: no
show_project_tag: no
show_due_date: yes
remove_completed_tasks: yes
debug: True
max_backups: 100
asana:
  - personal_access_token: x/xxxxxxxxxx...
    interval: 30
    tag: my_asana
    priority: 4
    task_params:
      workspace: breakingbad.com
      assignee: Walter White
icalendar:  
  - url: https://calendar.google.com/xxxxxx  # CalDav URL of your calendar, Google, Yandex, Nextcloud, any that supports it
    priority: 4
    tag: my_calendar
    interval: 30
local_timezone: Europe/London 
local_timezone_offset: 0 # Because I'm lazy, please enter your time offset in hours for your timezone above, negative or positive number
notifier_threshold_minutes: 15 # Since the script is running as a cronjob you should set this value to something greater than your cron interval. For example if it runs every minute - 5 minutes is a good option. If you run it every 5 minutes, then 10-15 minutes for this should be good. This is the default value. You can change it per task by using @notify30 @notify90 etc where numbers are the threshold override. You can have multiple different threshold labels per task to notify multiple times
homeassistant:
  hass_token: xxxxxxxxx # Home asssitant token which you can get from the UI under your user profile page (at least at the time of writing this)
  hass_url: http://192.168.1.2:8123 # Replace with your local or external home assistant url, *without* the trailing slash
  script_entity_id: script.my_notification # Script that will be triggered when event is processed. "title" and "message" attributes will be POSTed.
# auto_backlog:
#   project: Backlog
#   days_created: 30
#   days_due: 2
llm_tools:
  openedai:
    base_url: http://192.168.1.10:5000
    api_key: none
  smart_sort:
    prompt: |
            - Business - tasks related to anything that can provide direct income for the user, earn money, like work, job, business projects, tasks related to running a legal entity, and so on.
            - Family - tasks related to family, family health, kids, wife, parents, etc.
            - Personal - personal things, ideas, personal projects that are not directly related to business projects